# Generated by Django 4.0.4 on 2022-05-29 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('type_coffee', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='Barista/photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sweet', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='coffee/photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_coffee', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='coffee/photos/')),
                ('barista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userApp.barista')),
            ],
        ),
    ]
