# Generated by Django 4.0.4 on 2022-05-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='name',
            new_name='studentName',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='name',
            new_name='subjectName',
        ),
    ]
