# Generated by Django 4.0.4 on 2022-05-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_rename_name_students_studentname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
