# Generated by Django 4.0.4 on 2022-05-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_alter_subjects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='image',
            field=models.ImageField(upload_to='media/photos/'),
        ),
    ]
