# Generated by Django 4.0.4 on 2022-05-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=20)),
                ('namebook', models.CharField(max_length=30)),
                ('description', models.TextField(help_text='Here is the description of the book')),
                ('book', models.FileField(upload_to='books/pdf/')),
                ('image', models.ImageField(upload_to='books/images/')),
            ],
        ),
    ]
