# Generated by Django 4.0.4 on 2022-05-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date created'),
        ),
    ]
