# Generated by Django 4.0.4 on 2022-05-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type your full name', max_length=150)),
                ('email', models.EmailField(help_text='Type your Email', max_length=200)),
                ('subject', models.CharField(max_length=50)),
                ('importance', models.CharField(choices=[('VI', 'Very Important'), ('I', 'Important'), ('G', 'General'), ('NI', 'Not Important')], max_length=250)),
                ('desc', models.TextField()),
            ],
        ),
    ]
