# Generated by Django 4.0.4 on 2022-05-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suggestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='importance',
            field=models.CharField(choices=[('Very Important', 'Very Important'), ('Important', 'Important'), ('General', 'General'), ('Not Important', 'Not Important')], max_length=250),
        ),
    ]
