# Generated by Django 4.0.4 on 2022-05-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sweet', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='coffee/photos/')),
            ],
        ),
    ]
