# Generated by Django 4.0.4 on 2022-05-30 18:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the task owner', max_length=100)),
                ('image_field', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the task', max_length=100)),
                ('description', models.TextField(help_text='Description of the task', max_length=1000)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, help_text='Date of the created task')),
                ('name', models.ForeignKey(help_text='Name of the user', on_delete=django.db.models.deletion.CASCADE, to='ShowTasks.taskowner')),
            ],
        ),
    ]
