# Generated by Django 4.0.4 on 2022-05-30 19:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShowTasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskowner',
            name='name',
            field=models.CharField(max_length=100, verbose_name='The name of the task owner'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of the created task'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description of the task'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShowTasks.taskowner', verbose_name='The name of the task owner'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title of the task'),
        ),
    ]
