# Generated by Django 4.0.4 on 2022-05-29 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowTasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 1, 56, 20, 684867), help_text='Date of the created task'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(help_text='Description of the task', max_length=1000),
        ),
    ]
