# Generated by Django 4.0.4 on 2022-05-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Brand's Name", max_length=200)),
                ('overview', models.TextField(help_text='Brand Overview')),
                ('photo', models.ImageField(help_text='Brand Photo', upload_to='brand/photos/')),
                ('website', models.URLField(help_text="Brand's website.")),
            ],
        ),
    ]
