# Generated by Django 4.0.4 on 2022-05-29 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(help_text='The name of the Brand', max_length=50)),
                ('brand_description', models.TextField(help_text="brand's description")),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the product', max_length=50)),
                ('price', models.IntegerField(help_text="The product's price")),
                ('description', models.TextField(help_text="product's description")),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='the date & time of adding the product')),
                ('photo', models.ImageField(upload_to='products/images/')),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.brand')),
            ],
        ),
    ]
