# Generated by Django 4.0.4 on 2022-05-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_rename_name_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='bill',
            field=models.ImageField(null=True, upload_to='expense/bill_img'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
